# -*- coding: utf-8 -*-
"""arima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QcdSjydSVp7GgCFJmpr88ET8YISI6U20
"""

from statsmodels.tsa.arima.model import ARIMA
from tqdm import tqdm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
import matplotlib.dates as mdates

import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

# Device
print(f"Device available: {'CUDA' if torch.cuda.is_available() else 'CPU'}")

# ====== 1. Load data =======
df = pd.read_csv('FPT_train.csv')
df['time'] = pd.to_datetime(df['time'])
df = df.sort_values('time').reset_index(drop=True)

# ======= 2. Feature Creation ========
df['daily_return'] = df['close'].pct_change()
df['close_log'] = np.log(df['close'])
if df['daily_return'].isnull().sum() > 0:
    df['daily_return'].fillna(0, inplace=True)

def arima_predict(series, seq_len, pred_len, test_sample_indices, order=(5,1,1)):
    preds = []

    for idx in tqdm(test_sample_indices):
        # history = full data up to window start
        history_end = idx + seq_len
        history = series[:history_end]

        # fit ARIMA
        model = ARIMA(history, order=order).fit()

        # forecast next 7 days
        yhat = model.forecast(steps=pred_len)

        preds.extend(yhat)

    return np.array(preds)

seq_len = [7, 15, 30, 60, 120]
pred_len = 7
series = df['close_log'].dropna().reset_index(drop=True).values

for seq in seq_len:
  N = len(series) - seq - pred_len + 1

  train_end = int(N * 0.7)
  val_end   = train_end + int(N * 0.15)

  test_sample_indices = list(range(val_end, N))

  arima_pred_full = arima_predict(
    series, seq_len=seq, pred_len=7,
    test_sample_indices=test_sample_indices
  )

  arima_price = np.exp(arima_pred_full)
  target_len = 100
  arima_price_trimmed = arima_price[:target_len]

  df_arima = pd.DataFrame({
    'id': np.arange(1, target_len + 1),
    'close': arima_price_trimmed
  })

  df_arima.to_csv(f'arima_{seq}d.csv', index=False)

"""## Kèm loss"""

from statsmodels.tsa.arima.model import ARIMA
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from tqdm import tqdm


# ====== Load data =======
df = pd.read_csv('FPT_train.csv')
df['time'] = pd.to_datetime(df['time'])
df = df.sort_values('time').reset_index(drop=True)

df['daily_return'] = df['close'].pct_change()
df['close_log'] = np.log(df['close'])
df['daily_return'] = df['daily_return'].fillna(0)

series = df['close_log'].dropna().reset_index(drop=True).values


# ====== ARIMA prediction for test ======
def arima_predict(series, seq_len, pred_len, test_indices, order=(5,1,1)):
    preds = []
    for idx in tqdm(test_indices):
        history = series[:idx + seq_len]
        model = ARIMA(history, order=order).fit()
        yhat = model.forecast(steps=pred_len)
        preds.extend(yhat)
    return np.array(preds)


# ====== RUN for each seq len ======
seq_list = [7, 15, 30, 60, 120, 150, 190, 240, 480]
pred_len = 7

for seq in seq_list:
    print(f"\n========== SEQ_LEN = {seq} ==========")

    N = len(series) - seq - pred_len + 1
    train_end = int(N * 0.7)
    val_end   = train_end + int(N * 0.15)

    train_data = series[:train_end + seq]
    val_data   = series[train_end + seq : val_end + seq]
    test_indices = list(range(val_end, N))

    # ========= Fit ARIMA 1 lần cho TRAIN =========
    model = ARIMA(train_data, order=(5,1,1)).fit()


    # ========= Train Loss = fitted values =========
    train_pred = model.fittedvalues
    L = len(train_pred)

    train_true = train_data[-L:]

    train_mse = np.mean((train_pred - train_true)**2)
    train_mae = np.mean(np.abs(train_pred - train_true))

    print(f"Train MSE: {train_mse:.6f} | Train MAE: {train_mae:.6f}")

    # ========= Validation Loss (multi-step forecast) =========
    val_pred = model.forecast(steps=len(val_data))
    val_mse = np.mean((val_pred - val_data)**2)
    val_mae = np.mean(np.abs(val_pred - val_data))

    print(f"Val   MSE: {val_mse:.6f} | Val   MAE: {val_mae:.6f}")

    # ========= Test prediction (still rolling for test only) =========
    arima_pred_full = arima_predict(series, seq, pred_len, test_indices, order=(5,1,1))
    arima_price = np.exp(arima_pred_full)

    df_out = pd.DataFrame({
        "id": np.arange(1, 101),
        "close": arima_price[:100]
    })
    df_out.to_csv(f"arima_{seq}d.csv", index=False)

    print(f"Saved arima_{seq}d.csv")